name: Build

env:
  APKTOOL_VER: 2.9.3

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-java@v3
      with:
        distribution: 'adopt-hotspot'
        java-version: '8'

    - uses: robinraju/release-downloader@v1.8
      with:
        repository: 'iBotPeaches/Apktool'
        tag: 'v${{ env.APKTOOL_VER }}'
        fileName: 'apktool_${{ env.APKTOOL_VER }}.jar'

    - name: Build ImsService
      run: |
        java -jar apktool_${{ env.APKTOOL_VER }}.jar b ImsService

    - name: Build mediatek-telephony-base
      run: |
        java -jar apktool_${{ env.APKTOOL_VER }}.jar b mediatek-telephony-base

    - name: Prepare Artifacts
      run: |
        mkdir -p out
        cp ImsService/dist/ImsService.apk out/
        cp mediatek-telephony-base/dist/mediatek-telephony-base.jar out/

    - uses: actions/upload-artifact@v3
      with:
        name: Artifacts
        path: out
